name: lexical-selection-training

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check_config:
    name: Running check_config.py before installing the dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing python dependencies
        run: |
          sudo apt-get -qfy install python3-pip
          pip3 install -r requirements.txt
          
      - name: run
        run: python3 check_config.py tests/training/config.toml

  training:
    name: lexical selection training
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Running check_config.py(before installation of prerequisites)
      #   run: python3 check_config.py tests/training/config.toml

      - name: Installing apertium dependencies
        run: |
          sudo apt-get -qy update
          sudo apt-get -qfy install wget ca-certificates
          wget -q https://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
          sudo apt-get -qfy install --no-install-recommends apertium-all-dev

      - name: Checking out fast_align
        uses: actions/checkout@v2
        with:
          repository: clab/fast_align
          path: fast_align

      - name: Installing fast_align
        working-directory: fast_align
        run: |
          sudo apt-get -qfy install libgoogle-perftools-dev libsparsehash-dev
          mkdir build
          cd build
          cmake ..
          make -j4 VERBOSE=1 V=1
          cd ..

      - name: checking out apertium-eng-spa
        uses: actions/checkout@v2
        with:
          repository: apertium/apertium-eng-spa
          path: apertium-eng-spa

      - name: Installing apertium-eng-spa locally
        working-directory: apertium-eng-spa
        run: |
          autoreconf -fvi
          ./configure
          make -j4 VERBOSE=1 V=1

      - name: Installing python dependencies
        run: |
          sudo apt-get -qfy install python3-pip
          pip3 install -r requirements.txt
          
      - name: Training
        run: python3 lexical_training.py tests/training/config.toml
